require "json"

require "./arcana-ai/trace"
require "./arcana-ai/error"
require "./arcana-ai/context"
require "./arcana-ai/util/hash"
require "./arcana-ai/util/http"
require "./arcana-ai/util/multipart"
require "./arcana-ai/image/identity"
require "./arcana-ai/image/control"
require "./arcana-ai/image/request"
require "./arcana-ai/image/result"
require "./arcana-ai/image/provider"
require "./arcana-ai/image/runware"
require "./arcana-ai/image/openai"
require "./arcana-ai/chat/message"
require "./arcana-ai/chat/tool"
require "./arcana-ai/chat/server_tool"
require "./arcana-ai/chat/stream_event"
require "./arcana-ai/chat/request"
require "./arcana-ai/chat/response"
require "./arcana-ai/chat/provider"
require "./arcana-ai/chat/openai"
require "./arcana-ai/chat/anthropic"
require "./arcana-ai/chat/gemini"
require "./arcana-ai/tts/request"
require "./arcana-ai/tts/result"
require "./arcana-ai/tts/provider"
require "./arcana-ai/tts/openai"
require "./arcana-ai/tts/elevenlabs"
require "./arcana-ai/sfx/request"
require "./arcana-ai/sfx/result"
require "./arcana-ai/sfx/provider"
require "./arcana-ai/sfx/elevenlabs"
require "./arcana-ai/embed/request"
require "./arcana-ai/embed/result"
require "./arcana-ai/embed/provider"
require "./arcana-ai/embed/openai"
require "./arcana-ai/embed/voyage"
require "./arcana-ai/registry"

module Arcana
  module AI
    VERSION = "0.1.0"
  end
end
